server:
  port: 8050
  tomcat:
    max-threads: 200

spring:
  application:
    name: mish

  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5200MB

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:password@localhost:27100/mish-db?authSource=admin
      connection-pool:
        max-size: 200
        min-size: 60
    redis:
      host: localhost
      port: 7222
      password: mypassword

  security:
    oauth2:
      client:
        registration:
          dev-client:
            client-id: dev-client
            client-secret: secret
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          dev-client:
            issuer-uri: ${KEYCLOAK_URL:http://mish:8080}/auth/realms/${KEYCLOAK_REALM:mock-realm}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://mish:8080}/auth/realms/${KEYCLOAK_REALM:mock-realm}


ldap:
  base: "dc=example,dc=com"
  url: "ldap://localhost:389"
  user-dn-pattern: "uid={0},ou=users"


origin:
  url: http://localhost:8081

app:
  mongo:
    transaction:
      enabled: false
  page:
    limit: 20
    sort-direction: ASC
  security:
    role-claim-name: "realm_access.roles"
    role-claim-delimiter: "."
    email-claim: "email"
    user-id-claim: "sub"

logging:
  level:
    org:
      mongodb:
        driver: INFO
      springframework:
        security: DEBUG
        oauth2: DEBUG
        data:
          redis: DEBUG
          lettuce:
            core: DEBUG
