# shard mongod config (shard1/shard2/shard3)
systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true
storage:
  dbPath: /data/db
  journal:
    enabled: true
net:
  bindIpAll: true
  port: 27018
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/ssl/mongo/mongo.pem
    CAFile: /etc/ssl/mongo/ca.pem
processManagement:
  fork: false
replication:
  replSetName: rs-shard
security:
  authorization: enabled
  keyFile: /etc/ssl/mongo/keyfile
setParameter:
  enableLocalhostAuthBypass: true
