# mongos config (DO NOT set security.authorization here)
sharding:
  configDB: rs-config/cfg1:27019,cfg2:27020,cfg3:27021
net:
  bindIpAll: true
  port: 27017
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/ssl/mongo/mongo.pem
    CAFile: /etc/ssl/mongo/ca.pem
security:
  # mongos accepts keyFile (used for cluster authentication). Do NOT set authorization here.
  keyFile: /etc/ssl/mongo/keyfile
systemLog:
  destination: file
  path: /var/log/mongodb/mongos.log
  logAppend: true
setParameter:
  enableLocalhostAuthBypass: true
