storage:
  dbPath: /data/db
  journal:
    enabled: true
  wiredTiger:
      engineConfig:
        cacheSizeGB: 2

systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true

net:
  port: 27017
  bindIpAll: true

processManagement:
  fork: false

