services:
  mongo-main:
    image: mongo:6
    container_name: mongo-main
    hostname: mongo-main
    restart: no
    networks:
      - mish_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - ./certs-main/ca.pem:/etc/ssl/mongo/ca.pem:ro
      - ./certs-main/mongo.pem:/etc/ssl/mongo/mongo.pem:ro
      - ./keyfile/keyfile:/replication/keyfile
      - ./conf/mongod.conf:/etc/mongo/mongod.conf:ro
      - ./data-main:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username admin --password adminpassword --authenticationDatabase admin --tls --tlsCertificateKeyFile /etc/ssl/mongo/mongo.pem --tlsCAFile /etc/ssl/mongo/ca.pem --eval 'db.adminCommand(\"ping\")' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-replica-1:
    image: mongo:6
    container_name: mongo-replica-1
    hostname: mongo-replica-1
    restart: unless-stopped
    networks:
      - mish_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      SERVER_CN: mongo-replica-1
      OUTDIR: /etc/ssl/mongo
      CA_DIR: /shared/certs
    ports:
      - "27018:27017"
    volumes:
      - ./certs-replica-1/ca.pem:/etc/ssl/mongo/ca.pem:ro
      - ./certs-replica-1/mongo.pem:/etc/ssl/mongo/mongo.pem:ro
      - ./keyfile/keyfile:/replication/keyfile
      - ./scripts/generate-certs.sh:/docker-entrypoint-initdb.d/generate-certs.sh:ro
      - ./conf/mongod.conf:/etc/mongo/mongod.conf:ro
      - ./data-replica1:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username admin --password adminpassword --authenticationDatabase admin --tls --tlsCertificateKeyFile /etc/ssl/mongo/mongo.pem --tlsCAFile /etc/ssl/mongo/ca.pem --eval 'db.adminCommand(\"ping\")' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - mongo-main

  mongo-replica-2:
    image: mongo:6
    container_name: mongo-replica-2
    hostname: mongo-replica-2
    restart: unless-stopped
    networks:
      - mish_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      SERVER_CN: mongo-replica-2
      OUTDIR: /etc/ssl/mongo
      CA_DIR: /shared/certs
    ports:
      - "27019:27017"
    volumes:
      - ./certs-replica-2/ca.pem:/etc/ssl/mongo/ca.pem:ro
      - ./certs-replica-2/mongo.pem:/etc/ssl/mongo/mongo.pem:ro
      - ./keyfile/keyfile:/replication/keyfile
      - ./scripts/generate-certs.sh:/docker-entrypoint-initdb.d/generate-certs.sh:ro
      - ./conf/mongod.conf:/etc/mongo/mongod.conf:ro
      - ./data-replica2:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username admin --password adminpassword --authenticationDatabase admin --tls --tlsCertificateKeyFile /etc/ssl/mongo/mongo.pem --tlsCAFile /etc/ssl/mongo/ca.pem --eval 'db.adminCommand(\"ping\")' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - mongo-main

  mongo-replica-set-creator:
    image: mongo:6
    volumes:
      - ./certs-main/ca.pem:/etc/ssl/mongo/ca.pem
      - ./certs-main/mongo.pem:/etc/ssl/mongo/mongo.pem
      - ./scripts/initialize-replica-set.sh:/scripts/initialize-replica-set.sh:ro
    command: ["bash", "/scripts/initialize-replica-set.sh"]
    networks:
      - mish_net
    depends_on:
      - mongo-main
      - mongo-replica-1
      - mongo-replica-2


networks:
  mish_net:
    external: true